from .actor_serializer import ActorSerializer
from .director_serializer import DirectorSerializer
from .genre_serializer import GenreSerializer
from .movie_serializer import MovieSerializer
from .production_company_serializer import ProductionCompanySerializer
from .review_serializer import ReviewSerializer
