# Generated by Django 4.0.4 on 2022-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
