# Generated by Django 4.0.4 on 2022-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0002_alter_director_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
