# Generated by Django 4.0.4 on 2022-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0004_rename_release_year_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
