# Generated by Django 4.0.4 on 2022-06-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0005_actor_image_director_image_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
    ]
