# Generated by Django 4.0.4 on 2022-06-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0007_screameruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreamerUser',
        ),
    ]
