# Generated by Django 4.0.4 on 2022-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0009_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(through='screamer_api.MovieActor', to='screamer_api.actor'),
        ),
    ]
