# Generated by Django 4.0.4 on 2022-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0010_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.IntegerField(null=True),
        ),
    ]
