# Generated by Django 4.0.4 on 2022-06-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screamer_api', '0011_movie_movie_id_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(null=True, through='screamer_api.MovieActor', to='screamer_api.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_by', to='screamer_api.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screamer_api.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
